/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package order.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import order.model.Order;
import order.model.OrderModel;
import order.model.OrderSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Order service. Represents a row in the &quot;web_Order&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link OrderModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OrderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OrderImpl
 * @see Order
 * @see OrderModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class OrderModelImpl extends BaseModelImpl<Order> implements OrderModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a order model instance should use the {@link Order} interface instead.
	 */
	public static final String TABLE_NAME = "web_Order";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "orderNumber", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "orderStatus", Types.VARCHAR },
			{ "accountName", Types.VARCHAR },
			{ "orderStartDate", Types.TIMESTAMP },
			{ "createdBy", Types.VARCHAR },
			{ "location", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("orderNumber", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("orderStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("accountName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("orderStartDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("location", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table web_Order (uuid_ VARCHAR(75) null,orderNumber LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,orderStatus VARCHAR(75) null,accountName VARCHAR(75) null,orderStartDate DATE null,createdBy VARCHAR(75) null,location VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table web_Order";
	public static final String ORDER_BY_JPQL = " ORDER BY order_.accountName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY web_Order.accountName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(order.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.order.model.Order"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(order.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.order.model.Order"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(order.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.order.model.Order"), true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long LOCATION_COLUMN_BITMASK = 4L;
	public static final long ORDERSTATUS_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;
	public static final long ACCOUNTNAME_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Order toModel(OrderSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Order model = new OrderImpl();

		model.setUuid(soapModel.getUuid());
		model.setOrderNumber(soapModel.getOrderNumber());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setOrderStatus(soapModel.getOrderStatus());
		model.setAccountName(soapModel.getAccountName());
		model.setOrderStartDate(soapModel.getOrderStartDate());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setLocation(soapModel.getLocation());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Order> toModels(OrderSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Order> models = new ArrayList<Order>(soapModels.length);

		for (OrderSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(order.service.util.ServiceProps.get(
				"lock.expiration.time.order.model.Order"));

	public OrderModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _orderNumber;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOrderNumber(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _orderNumber;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Order.class;
	}

	@Override
	public String getModelClassName() {
		return Order.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("orderNumber", getOrderNumber());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("orderStatus", getOrderStatus());
		attributes.put("accountName", getAccountName());
		attributes.put("orderStartDate", getOrderStartDate());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("location", getLocation());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long orderNumber = (Long)attributes.get("orderNumber");

		if (orderNumber != null) {
			setOrderNumber(orderNumber);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String orderStatus = (String)attributes.get("orderStatus");

		if (orderStatus != null) {
			setOrderStatus(orderStatus);
		}

		String accountName = (String)attributes.get("accountName");

		if (accountName != null) {
			setAccountName(accountName);
		}

		Date orderStartDate = (Date)attributes.get("orderStartDate");

		if (orderStartDate != null) {
			setOrderStartDate(orderStartDate);
		}

		String createdBy = (String)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		String location = (String)attributes.get("location");

		if (location != null) {
			setLocation(location);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getOrderNumber() {
		return _orderNumber;
	}

	@Override
	public void setOrderNumber(long orderNumber) {
		_orderNumber = orderNumber;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getOrderStatus() {
		if (_orderStatus == null) {
			return "";
		}
		else {
			return _orderStatus;
		}
	}

	@Override
	public void setOrderStatus(String orderStatus) {
		_columnBitmask |= ORDERSTATUS_COLUMN_BITMASK;

		if (_originalOrderStatus == null) {
			_originalOrderStatus = _orderStatus;
		}

		_orderStatus = orderStatus;
	}

	public String getOriginalOrderStatus() {
		return GetterUtil.getString(_originalOrderStatus);
	}

	@JSON
	@Override
	public String getAccountName() {
		if (_accountName == null) {
			return "";
		}
		else {
			return _accountName;
		}
	}

	@Override
	public void setAccountName(String accountName) {
		_columnBitmask = -1L;

		_accountName = accountName;
	}

	@JSON
	@Override
	public Date getOrderStartDate() {
		return _orderStartDate;
	}

	@Override
	public void setOrderStartDate(Date orderStartDate) {
		_orderStartDate = orderStartDate;
	}

	@JSON
	@Override
	public String getCreatedBy() {
		if (_createdBy == null) {
			return "";
		}
		else {
			return _createdBy;
		}
	}

	@Override
	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@JSON
	@Override
	public String getLocation() {
		if (_location == null) {
			return "";
		}
		else {
			return _location;
		}
	}

	@Override
	public void setLocation(String location) {
		_columnBitmask |= LOCATION_COLUMN_BITMASK;

		if (_originalLocation == null) {
			_originalLocation = _location;
		}

		_location = location;
	}

	public String getOriginalLocation() {
		return GetterUtil.getString(_originalLocation);
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Order.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Order.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Order toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Order)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OrderImpl orderImpl = new OrderImpl();

		orderImpl.setUuid(getUuid());
		orderImpl.setOrderNumber(getOrderNumber());
		orderImpl.setGroupId(getGroupId());
		orderImpl.setCompanyId(getCompanyId());
		orderImpl.setUserId(getUserId());
		orderImpl.setUserName(getUserName());
		orderImpl.setCreateDate(getCreateDate());
		orderImpl.setModifiedDate(getModifiedDate());
		orderImpl.setOrderStatus(getOrderStatus());
		orderImpl.setAccountName(getAccountName());
		orderImpl.setOrderStartDate(getOrderStartDate());
		orderImpl.setCreatedBy(getCreatedBy());
		orderImpl.setLocation(getLocation());

		orderImpl.resetOriginalValues();

		return orderImpl;
	}

	@Override
	public int compareTo(Order order) {
		int value = 0;

		value = getAccountName().compareTo(order.getAccountName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Order)) {
			return false;
		}

		Order order = (Order)obj;

		long primaryKey = order.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		OrderModelImpl orderModelImpl = this;

		orderModelImpl._originalUuid = orderModelImpl._uuid;

		orderModelImpl._originalGroupId = orderModelImpl._groupId;

		orderModelImpl._setOriginalGroupId = false;

		orderModelImpl._originalCompanyId = orderModelImpl._companyId;

		orderModelImpl._setOriginalCompanyId = false;

		orderModelImpl._setModifiedDate = false;

		orderModelImpl._originalOrderStatus = orderModelImpl._orderStatus;

		orderModelImpl._originalLocation = orderModelImpl._location;

		orderModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Order> toCacheModel() {
		OrderCacheModel orderCacheModel = new OrderCacheModel();

		orderCacheModel.uuid = getUuid();

		String uuid = orderCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			orderCacheModel.uuid = null;
		}

		orderCacheModel.orderNumber = getOrderNumber();

		orderCacheModel.groupId = getGroupId();

		orderCacheModel.companyId = getCompanyId();

		orderCacheModel.userId = getUserId();

		orderCacheModel.userName = getUserName();

		String userName = orderCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			orderCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			orderCacheModel.createDate = createDate.getTime();
		}
		else {
			orderCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			orderCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			orderCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		orderCacheModel.orderStatus = getOrderStatus();

		String orderStatus = orderCacheModel.orderStatus;

		if ((orderStatus != null) && (orderStatus.length() == 0)) {
			orderCacheModel.orderStatus = null;
		}

		orderCacheModel.accountName = getAccountName();

		String accountName = orderCacheModel.accountName;

		if ((accountName != null) && (accountName.length() == 0)) {
			orderCacheModel.accountName = null;
		}

		Date orderStartDate = getOrderStartDate();

		if (orderStartDate != null) {
			orderCacheModel.orderStartDate = orderStartDate.getTime();
		}
		else {
			orderCacheModel.orderStartDate = Long.MIN_VALUE;
		}

		orderCacheModel.createdBy = getCreatedBy();

		String createdBy = orderCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			orderCacheModel.createdBy = null;
		}

		orderCacheModel.location = getLocation();

		String location = orderCacheModel.location;

		if ((location != null) && (location.length() == 0)) {
			orderCacheModel.location = null;
		}

		return orderCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", orderNumber=");
		sb.append(getOrderNumber());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", orderStatus=");
		sb.append(getOrderStatus());
		sb.append(", accountName=");
		sb.append(getAccountName());
		sb.append(", orderStartDate=");
		sb.append(getOrderStartDate());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", location=");
		sb.append(getLocation());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("order.model.Order");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orderNumber</column-name><column-value><![CDATA[");
		sb.append(getOrderNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orderStatus</column-name><column-value><![CDATA[");
		sb.append(getOrderStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accountName</column-name><column-value><![CDATA[");
		sb.append(getAccountName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orderStartDate</column-name><column-value><![CDATA[");
		sb.append(getOrderStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>location</column-name><column-value><![CDATA[");
		sb.append(getLocation());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Order.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Order.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _orderNumber;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _orderStatus;
	private String _originalOrderStatus;
	private String _accountName;
	private Date _orderStartDate;
	private String _createdBy;
	private String _location;
	private String _originalLocation;
	private long _columnBitmask;
	private Order _escapedModel;
}