/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package order.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Order service. Represents a row in the &quot;web_Order&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link order.model.impl.OrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link order.model.impl.OrderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Order
 * @see order.model.impl.OrderImpl
 * @see order.model.impl.OrderModelImpl
 * @generated
 */
@ProviderType
public interface OrderModel extends BaseModel<Order>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a order model instance should use the {@link Order} interface instead.
	 */

	/**
	 * Returns the primary key of this order.
	 *
	 * @return the primary key of this order
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this order.
	 *
	 * @param primaryKey the primary key of this order
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this order.
	 *
	 * @return the uuid of this order
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this order.
	 *
	 * @param uuid the uuid of this order
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the order number of this order.
	 *
	 * @return the order number of this order
	 */
	public long getOrderNumber();

	/**
	 * Sets the order number of this order.
	 *
	 * @param orderNumber the order number of this order
	 */
	public void setOrderNumber(long orderNumber);

	/**
	 * Returns the group ID of this order.
	 *
	 * @return the group ID of this order
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this order.
	 *
	 * @param groupId the group ID of this order
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this order.
	 *
	 * @return the company ID of this order
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this order.
	 *
	 * @param companyId the company ID of this order
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this order.
	 *
	 * @return the user ID of this order
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this order.
	 *
	 * @param userId the user ID of this order
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this order.
	 *
	 * @return the user uuid of this order
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this order.
	 *
	 * @param userUuid the user uuid of this order
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this order.
	 *
	 * @return the user name of this order
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this order.
	 *
	 * @param userName the user name of this order
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this order.
	 *
	 * @return the create date of this order
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this order.
	 *
	 * @param createDate the create date of this order
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this order.
	 *
	 * @return the modified date of this order
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this order.
	 *
	 * @param modifiedDate the modified date of this order
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the order status of this order.
	 *
	 * @return the order status of this order
	 */
	@AutoEscape
	public String getOrderStatus();

	/**
	 * Sets the order status of this order.
	 *
	 * @param orderStatus the order status of this order
	 */
	public void setOrderStatus(String orderStatus);

	/**
	 * Returns the account name of this order.
	 *
	 * @return the account name of this order
	 */
	@AutoEscape
	public String getAccountName();

	/**
	 * Sets the account name of this order.
	 *
	 * @param accountName the account name of this order
	 */
	public void setAccountName(String accountName);

	/**
	 * Returns the order start date of this order.
	 *
	 * @return the order start date of this order
	 */
	public Date getOrderStartDate();

	/**
	 * Sets the order start date of this order.
	 *
	 * @param orderStartDate the order start date of this order
	 */
	public void setOrderStartDate(Date orderStartDate);

	/**
	 * Returns the created by of this order.
	 *
	 * @return the created by of this order
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this order.
	 *
	 * @param createdBy the created by of this order
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the location of this order.
	 *
	 * @return the location of this order
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this order.
	 *
	 * @param location the location of this order
	 */
	public void setLocation(String location);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Order order);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Order> toCacheModel();

	@Override
	public Order toEscapedModel();

	@Override
	public Order toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}